name: Deploy static
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy static files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      # - name: Build and export next
      #   run: npm run build
      
      - name: Adds .nojekyll
        run: touch .nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .